// <auto-generated />
namespace GamblingNewbies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addWinLossTimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWinLossTimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201408061618480_addWinLossTimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
